### PR TITLE
Development

### PR DESCRIPTION
**Pull request by zlayabekrija**
Kindly review the code .
Thanks :)

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @zlayabekrija @inhaq  !

Glad to review this for you :-)

The UI looks awesome! I think you made it look like the old Apple page.
[On my screen](https://htmlpreview.github.io/?https://raw.githubusercontent.com/zlayabekrija/apple-clone/development/index.html), the intro image doesn't span across the whole page, and leaves an equal margin on the left and right side, that is not same as the bottom area. Was this intended?

As for the code, this was perfectly done! 👍

**Comment by inhaq** [comment]
Hi @talihomz thanks for the review. We developed [this site](https://web.archive.org/web/20140301004610/http://www.apple.com/) as required. Kindly share SS and browser info as it looks fine in our browsers and screens.

**Comment by talihomz** [comment]
screenshot 2018-12-09 at 6 32 13 pm

Browser: Google Chrome - Chrome OS Version 70.0.3538.110 (Official Build) (64-bit)
Screen: 13", Resolution: 1536 x 864

**Comment by inhaq** [comment]
Thanks for the details. @talihomz kindly review it.

**Comment by talihomz** [comment]
Awesomely done @inhaq @zlayabekrija 

Its a 👍 from me!

**Pull request merged**
